package com.imzoee.caikid.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORDER.
 */
public class Order {

    private Integer orderId;
    private String orderNumber;
    private String phone;
    private String name;
    private Double price;
    private String recieveTime;
    private String orderTime;
    private String orderFlag;

    public Order() {
    }

    public Order(Integer orderId, String orderNumber, String phone, String name, Double price, String recieveTime, String orderTime, String orderFlag) {
        this.orderId = orderId;
        this.orderNumber = orderNumber;
        this.phone = phone;
        this.name = name;
        this.price = price;
        this.recieveTime = recieveTime;
        this.orderTime = orderTime;
        this.orderFlag = orderFlag;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getRecieveTime() {
        return recieveTime;
    }

    public void setRecieveTime(String recieveTime) {
        this.recieveTime = recieveTime;
    }

    public String getOrderTime() {
        return orderTime;
    }

    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime;
    }

    public String getOrderFlag() {
        return orderFlag;
    }

    public void setOrderFlag(String orderFlag) {
        this.orderFlag = orderFlag;
    }

}
