package com.imzoee.caikid.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECIPE.
 */
public class Recipe {

    private Integer id;
    private String name;
    private String info;
    private String img_path;
    private Double price;
    private Integer stock;
    private Integer sales;
    private Integer status;
    private String desc;

    public Recipe() {
    }

    public Recipe(Integer id, String name, String info, String img_path, Double price, Integer stock, Integer sales, Integer status, String desc) {
        this.id = id;
        this.name = name;
        this.info = info;
        this.img_path = img_path;
        this.price = price;
        this.stock = stock;
        this.sales = sales;
        this.status = status;
        this.desc = desc;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getImg_path() {
        return img_path;
    }

    public void setImg_path(String img_path) {
        this.img_path = img_path;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Integer getStock() {
        return stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    public Integer getSales() {
        return sales;
    }

    public void setSales(Integer sales) {
        this.sales = sales;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

}
